routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;
use App\Controllers;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SessionsController;

Route::get('/login', "App\Http\Controllers\SessionsController@create")->name('login.create');
Route::post('/login', "App\Http\Controllers\SessionsController@store")->name('login.store');
Route::post('/logout', [SessionsController::class,'logout']);
Route::get('/', "App\Http\Controllers\SessionsController@create")->name('login.create');

Route::get('home', "App\Http\Controllers\HomeController@index")->name('home');
Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);
Route::resource('cuadrillas', App\Http\Controllers\CuadrillaController::class);
Route::resource('sectores', App\Http\Controllers\SectorController::class);
// Route::resource('tipos-trabajo', App\Http\Controllers\TiposTrabajoController::class);
// Route::resource('motivos-trabajo', App\Http\Controllers\MotivosTrabajoController::class);
Route::resource('asignar-tt-a-cuadrilla', App\Http\Controllers\AsignarTTaCuadrillaController::class);
	//Route::resource('asignar-motivo-a-sector', App\Http\Controllers\AsignarMotivoASectorController::class);

Route::post('asignar-tt-a-cuadrilla_ajax', "App\Http\Controllers\AsignarTTaCuadrillaController@cuadrilla_ajax")->name('cuadrilla_ajax');

//});

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Usuario
 *
 * @property $id
 * @property $legajo
 * @property $apellido
 * @property $nombre
 * @property $cuadrilla_id
 * @property $operario_id
 * @property $nombre_usuario
 * @property $servicio_id
 * @property $sector_id
 * @property $remember_token
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Usuario extends Model
{
    
    static $rules = [
		'legajo' => '',
		'apellido' => 'required',
		'nombre' => 'required',
		'cuadrilla_id' => 'required',
		'operario_id' => '',
		'nombre_usuario' => 'required',
		'servicio_id' => 'required',
		'sector_id' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['legajo','apellido','nombre','cuadrilla_id','operario_id',
																	'nombre_usuario','servicio_id','sector_id'];


		public function Cuadrilla()
		{
			return	$this->hasOne('App\Models\Cuadrilla');
		}

	


}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class UsuarioController extends Controller
{
	public function index()
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$usuariosGea = DB::connection('GeaCorpico')->table('OPERARIO')->get();
		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn
		//OPERARIOS trae de la BD ASP
		$operarios = DB::table('AspNetUsers')
			->select('AspNetUsers.Id as IdUser', 'AspNetUsers.*', 'AspNetUserRoles.*', 'AspNetRoles.*')
			->where('Servicio', '=', $serv)
			->leftJoin('AspNetUserRoles', 'UserId', '=', 'AspNetUsers.Id')
			->leftJoin('AspNetRoles', 'AspNetRoles.Id', '=', 'AspNetUserRoles.RoleId')
			->get();
		$arrayCuadrillas = Http::get(config('constants.APP_API_HOST') . "/TIPO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();

		return view('usuario.index', compact('operarios'))
			->with('cuadrillas', $arrayCuadrillas)
			->with('usuarios', $usuariosGea);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$usuariosGea = DB::connection('GeaCorpico')->table('OPERARIO')->get();
		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn

		$operarios = Http::get(config('constants.APP_API_HOST') . "/OPERARIOS/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		$servicios = Http::get(config('constants.APP_API_HOST') . "/TIPO_EMPRESA/?update=2018-01-01")->json();
		$sectores = Http::get(config('constants.APP_API_HOST') . "/SECTORS/?servicio=$serv&update=2018-01-01")->json();
		$cuadrillas = Http::get(config('constants.APP_API_HOST') . "/TIPO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin

		if ($rol == 2) {
			foreach ($servicios as $servicio) {
				if ($servicio['TIE_ID'] == $serv) {
					$nombreServicio = $servicio['TIE_DESCRIPCION'];
					foreach ($sectores as $sector) {
						if ($sector['SEC_ID'] == $sec) {
							$nombreSector = $sector['SEC_DESCRIPCION'];
						}
					}
				}
			}
		} else {
			foreach ($servicios as $servicio) {
				if ($servicio['TIE_ID'] == $serv) {
					$nombreServicio = $servicio['TIE_DESCRIPCION'];
				}
			}

			$nombreSector = '';
		}

		return view('usuario.create')
			->with('usuariosGea', $usuariosGea)
			->with('usuarios', $operarios)
			->with('rol', $rol)
			->with('idServicio', $serv)
			->with('nombreServicio', $nombreServicio)
			->with('nombreSector', $nombreSector)
			->with('idSector', $sec)
			->with('cuadrillas', $cuadrillas)
			->with('sectores', $sectores);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$datos = $request->all();

		if (isset($datos['descripcionGeasys'])) {
			$ultimoUsuarioregistrado = DB::connection('GeaCorpico')->table('OPERARIO')->orderBy('OPE_ID', 'desc')->first();
			$idSiguiente = $ultimoUsuarioregistrado->OPE_ID + 1;

			DB::connection('GeaCorpico')->table('OPERARIO')->insert(
				[
					'OPE_ID' => (string)$idSiguiente,
					'OPE_DESCRIPCION' => $datos['descripcionGeasys'],
					'OPE_CONTRATISTA' => "1",
					'OPE_SUCURSAL' => "1",
					'OPE_ACTIVO' => "S",
					'OPE_ID_USER' => session()->get('usuarioReg_userName'),
					'OPE_FECHA_UPDATE' => now()
				]
			);
			return redirect("/usuarios/create")
				->with('success', 'Operario creado correctamente.');;
		}

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin
		$servicios = Http::get(config('constants.APP_API_HOST') . "/TIPO_EMPRESA/?update=2018-01-01")->json();

		if ($rol == 2) {
			foreach ($servicios as $servicio) {
				if ($servicio['TIE_ID'] == $serv) {
					$servicio_id = $servicio['TIE_ID'];
				}
			}
		} else {
			foreach ($servicios as $servicio) {
				if ($servicio['TIE_ID'] == $serv) {
					$servicio_id = $servicio['TIE_ID'];
				}
			}
		}

		if (isset($datos['operario'])) {

			$campos = Validator::make($request->all(), [
				'operario_id'    => 'required',
				'apellido' => 'required',
				'nombre' => 'required',
				'usuarioOperario' => 'required'
			]);

			//genero clave automatica si asi lo decide el usuario formato="ar1948so"
			if ($datos['chec1'] == 'on') {
				$array = str_split($datos['usuarioOperario']);
				$letra1 = $array[0];
				$letra2 =	substr($datos['usuarioOperario'], -1);
				$letra3 = $array[1];
				$letra4 = substr($datos['usuarioOperario'], -2, 1);

				$passwordOperario = $letra1 . $letra2 . '1948' . $letra3 . $letra4;
				$confirmPasswordOperario = $passwordOperario;
			} else {
				if ($datos['chec1'] == 'off') {
					$passwordOperario = $datos['newPasswordOperario'];
					$confirmPasswordOperario = $datos['confirmNewPasswordOperario'];
				}
			}

			$servicio = (string)$servicio_id;
			//controlo que las contraseñas ingresadas sean iguales (-1) si no lo son
			$passIguales = strcmp($passwordOperario, $confirmPasswordOperario);

			if ($campos->fails() || $passIguales !== 0) {
				return redirect()->route('usuarios.index')
					->with('error', 'ERROR al generar un usuario');
			}
			dd($datos);
			$usuario = Http::post(
				config('constants.APP_API_HOST') . "/Account/Register/",
				[
					'Servicio' => $servicio,
					'Sector' => (string)$datos['sector_id_operario'],
					'Operario' => (string)$datos['operario_id'],
					'Cuadrilla' => 0,
					'TipoCuadrilla' => 0,
					'Apellido' => $datos['apellido'],
					'Nombre' => $datos['nombre'],
					'Password' => $passwordOperario,
					'ConfirmPassword' => $confirmPasswordOperario,
					'UserName' => $datos['usuarioOperario']
				]
			);

			// ACA DEBE GUARDARSE TAMBIEN EN TABLA AspNetUserRoles EL ID OPERARIO Y EL ROL
			//Traigo el user agregado para tomar el ID generado e insertarlo en la tabla
			$usuarioAgregado = DB::connection('sqlsrv')->table('AspNetUsers')
				->where('Operario', '=', (string)$datos['operario_id'])
				->where('UserName', $datos['usuarioOperario'])
				->get();

			DB::table('AspNetUserRoles')->insert(
				['UserId' => $usuarioAgregado[0]->Id, 'RoleId' => "3"]
			);
			return redirect()->route('usuarios.index')
				->with('success', 'Usuario creado correctamente');
		}

		if (isset($datos['supervisor'])) {

			$campos = Validator::make($request->all(), [
				'operario_id'    => 'required',
				'apellido' => 'required',
				'nombre' => 'required',
				'usuarioSupervisor' => 'required'
			]);

			//genero clave automatica si asi lo decide el usuario formato="ar1948so"
			if ($datos['chec2'] == 'on') {
				$array = str_split($datos['usuarioSupervisor']);
				$letra1 = $array[0];
				$letra2 =	substr($datos['usuarioSupervisor'], -1);
				$letra3 = $array[1];
				$letra4 = substr($datos['usuarioSupervisor'], -2, 1);

				$passwordSupervisor = 's' . $letra2 . '1948' . $letra3 . $letra4;
				$confirmPasswordSupervisor = $passwordSupervisor;
			} else {
				if ($datos['chec2'] == 'off') {
					$passwordSupervisor = $datos['newPasswordSupervisor'];
					$confirmPasswordSupervisor = $datos['confirmNewPasswordSupervisor'];
				}
			}
			$servicio = (string)$servicio_id;

			//controlo que las contraseñas ingresadas sean iguales (-1) si no lo son
			$passIguales = strcmp($passwordSupervisor, $confirmPasswordSupervisor);

			if ($campos->fails() || $passIguales !== 0) {
				return redirect()->back()
					->with('error', 'ERROR al actualizar el usuario');
			}

			$usuario = Http::post(
				config('constants.APP_API_HOST') . "/Account/Register/",
				[
					'Servicio' => $servicio,
					'Sector' => 	(string)$datos['sector_id_supervisor'],
					'Operario' => (string)$datos['operario_id'],
					'Cuadrilla' => 0,
					'TipoCuadrilla' => 0,
					'Apellido' => $datos['apellido'],
					'Nombre' => $datos['nombre'],
					'Password' => $passwordSupervisor,
					'ConfirmPassword' => $confirmPasswordSupervisor,
					'UserName' => $datos['usuarioSupervisor']
				]
			);

			// ACA DEBE GUARDARSE TAMBIEN EN TABLA AspNetUserRoles EL ID OPERARIO Y EL ROL
			//Traigo el user agregado para tomar el ID generado e insertarlo en la tabla
			$usuarioAgregado = DB::connection('sqlsrv')->table('AspNetUsers')
				->where('Operario', '=', (string)$datos['operario_id'])
				->where('UserName', $datos['usuarioSupervisor'])
				->get();

			DB::table('AspNetUserRoles')->insert(
				['UserId' => $usuarioAgregado[0]->Id, 'RoleId' => "2"]
			);
		}
		return redirect()->route('usuarios.index')
			->with('success', 'Usuario creado correctamente');
	}

	public function show($id)
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin

		$usuario = DB::table('AspNetUsers')
			->where('Id', $id)
			->get();

		//$usuarios = Http::get(config('constants.APP_API_HOST')."/OPERARIOS/?servicio=3&sector=5&update=2018-01-01")->json();

resources/views/usuario/create.blade.php
@extends('adminlte::page')

@section('title', 'Usuario')
@section('plugins.Select2',true)
@section('content_header')
<h1>Usuario</h1>
@stop


@section('content')
<section class="content container-fluid">


	<div class="row">
		<div class="col-md-12">

			@includeif('partials.errors')
			<div class="card card-default">
				<div class="card-header">
					<span class="card-title">Nuevo Usuario</span>
				</div>
				<div class="card-body">
					<form method="POST" action="{{ route('usuarios.store') }}" role="form" enctype="multipart/form-data">
						@csrf
						@include('usuario.form')
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/usuario/edit.blade.php
		@extends('adminlte::page')
		@section('title', 'Usuario')
		@section('content_header')
		<h1>Modificar Usuario</h1>
		@stop

		@section('plugins.Select2', true)

		@section('content')
		<section class="content container-fluid">
			<div class="">
				<div class="col-md-12">

					@includeif('partials.errors')

					<div class="card card-default">
						<div class="card-header">
							<span class="card-title">Modificar Operario </span><span style="float:right; border: 2px solid green"> Solo podrá <b>eliminar el usuario</b> desde el listado USUARIOS</span>
						</div>
						<div class="card-body">
							<form method="POST" action="{{ route('usuarios.update', $id) }}" role="form" enctype="multipart/form-data">

								{{ method_field('PATCH') }}
								@csrf

								<div class="box box-info padding-1">
									<div class="box-body row col-md-12">
										<div class="col-md-6">

		
											<div class="form-group col-md-12">
												{{ Form::label('Servicio ') }}<br>
												<input type="text" name="servicio" class="form-control" disabled value="{{$nombreServicio}}">
												<div class="form-group col-md-12">
															{{ Form::hidden('servicio', $id_servicio, ['class' => 'form-control' ]) }}
														</div>
											</div>

											<div class="box-body row col-md-12" style="border:3px double; border-radius:10px">
												<div class="form-group col-md-6">
													<span>Rol del usuario:</span>
												</div>
												<div class="form-group checkbox col-md-6">
													@if($usuarioOpe != [])
													<input name="operario" checked value="on" type="checkbox" id="operario" class="operario" />
													@else
													<input name="operario" type="checkbox" value="off" id="operario" class="operario" />
													@endif
													<label for="operario">Operario </label><br>
													@if($usuarioSup != [])
													<input name="supervisor" value="on" checked type="checkbox" id="supervisor" class="supervisor" />
													@else
													<input name="supervisor" value="off" type="checkbox" id="supervisor" class="supervisor" />
													@endif

													<label for="supervisor">Supervisor </label><br>
												</div>
											</div>
										</div>
										<div class="box-body row col-md-6">
											<div class="form-group col-md-12">
												{{ Form::label('Operario') }}<br>
												{{$usuarioGea->OPE_DESCRIPCION}} - {{$usuarioGea->OPE_ID}}
											</div>
											<div class="form-group col-md-6">
												{{ Form::label('Apellido') }}
												{{ Form::text('apellido', $usuario->Apellido, ['class' => 'form-control', 'placeholder' => 'Apellido', 'required'=>'required']) }}
											</div>
											<div class="form-group col-md-6">
												{{ Form::label('Nombre') }}
												{{ Form::text('nombre', $usuario->Nombre, ['class' => 'form-control', 'placeholder' => 'Nombre', 'required'=>'required']) }}
											</div>

										</div>

										<div class="form-group col-md-6" id="contenidoOperario">
											<hr>
											<div class="card card-default">

												<div class="card-header" style="background-color:#007e3a">
													<span class="card-title">Registro como Operario</span>
												</div>
												<div class="card-body">
													<div class="box box-info padding-1">
														<div class="box-body row col-md-12">
															<div class="form-group col-md-12">
																{{ Form::label('Nombre Usuario Sugerido') }}
																{{ Form::text('usuarioOperario', $nombreUsuarioOpe, ['class' => 'form-control', 'id'=>'usuarioOperario', 'placeholder' => 'Nombre Usuario Operario']) }}
															</div>
														</div>
														<div class="box-body row col-md-12">

															{{ Form::label('Sector') }}: {{$sectorOpeNombre}}

															<select name='sector_id_operario' style="width:100%" id='sector_id_operario' class=" row form-control js-example-basic-single">
																<option value="#">Seleccione Nuevo Sector</option>
																@foreach($sectores as $sector)
																<option value="{{$sector['SEC_ID']}}">{{$sector['SEC_DESCRIPCION']}}</option>
																@endforeach
															</select>
														</div>
														<hr>
														<input name="chec1" checked type="checkbox" id="chec1" onchange="comprobar1();" />
														<label for="chec1">Generar/Modificar Contraseña automáticamente </label><br>
														<span style="font-size:12px">Ej: Us: <b>mdelvalle</b> - Formato de clave: <b>me1948dl</b></span>

												
														<div class="form-group col-md-12">
															{{ Form::label('Nueva Contraseña') }}
															{{ Form::password('newPasswordOperario', ['class' => 'form-control','id'=>'newPasswordOperario', 'attribute' => 'value','readonly']) }}
														</div>
														<div class="form-group col-md-12">
															{{ Form::label('Confirmar Contraseña') }}
															{{ Form::password('confirmNewPasswordOperario', ['class' => 'form-control','id'=>'confirmNewPasswordOperario', 'attribute' => 'value','readonly']) }}
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="form-group col-md-6" id="contenidoSupervisor">
											<hr>
											<div class="card card-default">

												<div class="card-header" style="background-color:#007e3a">
													<span class="card-title">Registro como Supervisor</span>
												</div>
												<div class="card-body">
													<div class="box box-info padding-1">
														<div class="box-body row col-md-12">
															<div class="form-group col-md-12">
																{{ Form::label('Nombre Usuario Sugerido') }}
																{{ Form::text('usuarioSupervisor', $nombreUsuarioSup, ['class' => 'form-control', 'id'=>'usuarioSupervisor', 'placeholder' => 'Nombre Usuario Supervisor', 'required']) }}

															</div>
														</div>
														<div class="box-body row col-md-12">

															{{ Form::label('Sector') }}: {{$sectorSupNombre}}
															<select name='sector_id_supervisor' style="width:100%" id='sector_id_supervisor' class=" row form-control js-example-basic-single">
																<option value="#">Seleccione Nuevo Sector</option>

																@foreach($sectores as $sector)
																<option value="{{$sector['SEC_ID']}}">{{$sector['SEC_DESCRIPCION']}}</option>
																@endforeach
															</select>
														</div>
														<hr>
														<input name="chec2" checked type="checkbox" id="chec2" onchange="comprobar2();" />
														<label for="chec2">Generar/Modificar Contraseña automática </label><br>
														<span style="font-size:12px">Ej: Us: <b>smdelvalle</b> - Formato de clave: <b>se1948ml</b></span>
														<div class="form-group col-md-12">
															{{ Form::label('Nueva Contraseña') }}
															{{ Form::password('newPasswordSupervisor', ['class' => 'form-control','id'=>'newPasswordSupervisor', 'attribute' => 'value','readonly']) }}
														</div>
														<div class="form-group col-md-12">
															{{ Form::label('Confirmar Contraseña') }}
															{{ Form::password('confirmNewPasswordSupervisor', ['class' => 'form-control','id'=>'confirmNewPasswordSupervisor', 'attribute' => 'value','readonly']) }}
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="box-footer mt20 col-md-12">
											<hr>
											<button type="submit" class="btn btn-primary">Guardar</button>
										</div>
									</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</section>
		@endsection


		@section('js')
		<script>
			$(document).ready(function() {
				$('.js-example-basic-single').select2();
			});

			function comprobar1() {
				document.getElementById('newPasswordOperario').readOnly = document.getElementById("chec1").checked;
				document.getElementById('confirmNewPasswordOperario').readOnly = document.getElementById("chec1").checked;
			}

			function comprobar2() {
				document.getElementById('newPasswordSupervisor').readOnly = document.getElementById("chec2").checked;
				document.getElementById('confirmNewPasswordSupervisor').readOnly = document.getElementById("chec2").checked;
			}
		</script>
		<script type="text/javascript">
			if (document.getElementById("operario").value == 'on') {
				$('#contenidoOperario').show();
			} else {
				$('#contenidoOperario').hide();
			}

			$(function() {

				$('.operario').change(function() {
					if (!$(this).prop('checked')) {
						$('#contenidoOperario').hide();
					} else {
						$('#contenidoOperario').show();
					}

				})
			});


			if (document.getElementById("supervisor").value == 'on') {
				$('#contenidoSupervisor').show();
			} else {
				$('#contenidoSupervisor').hide();
			}

			$(function() {
				$('.supervisor').change(function() {
					if (!$(this).prop('checked')) {
						$('#contenidoSupervisor').hide();
					} else {
						$('#contenidoSupervisor').show();
					}

				})
			});

			$("#usuarioOperario").change(function() {
				Swal.fire({
					html: `<h1>Sugerencia</h1>
			<p>El campo <strong>Usuario Sugerido del Operario</strong> ha cambiado. Debería actualizar la contraseña</p>
			`,
				});
			});

			$("#usuarioSupervisor").change(function() {
				Swal.fire({
					html: `<h1>Sugerencia</h1>
			<p>El campo <strong>Usuario Sugerido del Supervisor</strong> ha cambiado. Debería actualizar la contraseña</p>
			`,
				});
			});
		</script>
		@endsection

resources/views/usuario/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuarios')

@section('content_header')
<h1>Usuarios</h1>

@stop


@section('content')
<div class="container-fluid">
	@if (session('success'))
	<div class="alert alert-success" role="success">
		{{ session('success') }}
	</div>
	@endif
	@if (session('error'))
	<div class="alert alert-error" role="error">
		{{ session('error') }}
	</div>
	@endif

	<div class="row">

		<div class="col-sm-12">
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: space-between; align-items: center;">
						<span id="card_title">
							{{ __('Lista de Usuarios') }}
						</span>

						<div class="float-right">
							<a href="{{ route('usuarios.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
								{{ __('Nuevo Usuario') }}
							</a>
						</div>
					</div>
				</div>

				<div class="card-body">
					<div class="table-responsive">
						<table id="usuarios" class="table table-striped table-hover">
							<thead class="thead">
								<tr>
									<th style="width:25%">Nombre</th>
									<th style="width:15%">Rol</th>
									<th>Operario</th>
									<th>Nombre Usuario</th>
									<th style="width:15%"></th>
								</tr>
							</thead>
							<tbody>
								@foreach ($operarios as $usuario)

								<tr>
									<td>{{ $usuario->Apellido }}, {{ $usuario->Nombre}}</td>
									<td>{{ $usuario->Name}}</td>
									<td>{{ $usuario->Operario}}</td>
									<td>{{ $usuario->UserName}}</td>
									<td>
										<form action="{{ route('usuarios.destroy',$usuario->IdUser) }}" method="POST">
											<a class="btn btn-sm btn-success" href="{{ route('usuarios.edit',$usuario->IdUser) }}"><i class="fa fa-fw fa-edit"></i></a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger borrar btn-sm"><i class="fa fa-fw fa-trash"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
	$(document).ready(function() {
		$('#usuarios').DataTable({
			"language": {
				"search": "Buscar",
				"lengthMenu": "Mostrar _MENU_ registros por página",
				"info": "Mostrando página _PAGE_ de _PAGES_",
				"paginate": {
					"previous": "Anterior",
					"next": "Siguiente",
					"first": "Primero",
					"last": "Ultimo"

				}
			}
		});
	});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>

<script type="text/javascript">
	$('.borrar').click(function(event) {
		var form = $(this).closest("form");
		var name = $(this).data("name");
		event.preventDefault();
		swal({
				title: `Eliminar Usuario`,
				text: "El usuario puede estar asignado a una cuadrilla. DESEA CONTINUAR?",
				icon: "warning",
				buttons: true,
				dangerMode: true,
			})

			.then((willDelete) => {
				if (willDelete) {
					form.submit();
				}
			});
	});
</script>

@endsection