routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;
use App\Controllers;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SessionsController;

Route::get('/login', "App\Http\Controllers\SessionsController@create")->name('login.create');
Route::post('/login', "App\Http\Controllers\SessionsController@store")->name('login.store');
Route::post('/logout', [SessionsController::class,'logout']);
Route::get('/', "App\Http\Controllers\SessionsController@create")->name('login.create');

Route::get('home', "App\Http\Controllers\HomeController@index")->name('home');
Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);
Route::resource('cuadrillas', App\Http\Controllers\CuadrillaController::class);
Route::resource('sectores', App\Http\Controllers\SectorController::class);
// Route::resource('tipos-trabajo', App\Http\Controllers\TiposTrabajoController::class);
// Route::resource('motivos-trabajo', App\Http\Controllers\MotivosTrabajoController::class);
Route::resource('asignar-tt-a-cuadrilla', App\Http\Controllers\AsignarTTaCuadrillaController::class);
	//Route::resource('asignar-motivo-a-sector', App\Http\Controllers\AsignarMotivoASectorController::class);

Route::post('asignar-tt-a-cuadrilla_ajax', "App\Http\Controllers\AsignarTTaCuadrillaController@cuadrilla_ajax")->name('cuadrilla_ajax');

//});

app/Models/AsignarTTaCuadrilla.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AsignarTTaCuadrilla extends Model
{
    use HasFactory;
}

app/Http/Controllers/AsignarTTaCuadrillaController.php
<?php

namespace App\Http\Controllers;

use App\Models\AsignarTTaCuadrilla;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\DB;
use App\Models\Cuadrilla;
use App\Models\Sector;
use App\Models\TipoServicio;
use App\Config\constants;
use Illuminate\Http\Request;

class AsignarTTaCuadrillaController extends Controller
{

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin

		// $roles[0]   = array('1', 'Admin');
		// $roles[1]   = array('2', 'Supervisor');
		// $roles[2]   = array('3', 'Operario');
		/*
		el usuario logueado pertenece a un sector y 1 servicio, a partir de ahi, obtengo tipo_trabajo_Cuadrilla
		por lo tanto a partir de ahi traigo cuadrillas y tipos de trabajo
		*/
		$list_cuadrillas = Http::get(config('constants.APP_API_HOST') . "/TIPO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();

		return view('asignar-tt-a-cuadrilla.index', compact('list_cuadrillas'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		//$cuadrilla = new Cuadrilla();
		return view('cuadrilla.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin

		// $roles[0]   = array('1', 'Admin');
		// $roles[1]   = array('2', 'Supervisor');
		// $roles[2]   = array('3', 'Operario');

		//	$list_usuarios = Http::get(config('constants.APP_API_HOST')."/OPERARIOS/?servicio=3&sector=5&update=2018-01-01");

		/*
		el usuario logueado pertenece a un sector y 1 servicio, a partir de ahi, obtengo tipo_trabajo_Cuadrilla
		por lo tanto a partir de ahi traigo cuadrillas y tipos de trabajo
		
		*/
		// $list_tt_cuadrilla = Http::get(config('constants.APP_API_HOST') . "/TIPO_TRABAJO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		$list_cuadrillas = Http::get(config('constants.APP_API_HOST') . "/TIPO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		// $list_tt = Http::get(config('constants.APP_API_HOST') . "/TIPO_TRABAJO_OPERATIVO/")->json();

		return view('asignar-tt-a-cuadrilla.index', compact('list_cuadrillas'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  \App\Models\AsignarTTaCuadrilla  $asignarTTaCuadrilla
	 * @return \Illuminate\Http\Response
	 */
	public function show(AsignarTTaCuadrilla $asignarTTaCuadrilla)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Models\AsignarTTaCuadrilla  $asignarTTaCuadrilla
	 * @return \Illuminate\Http\Response
	 */
	public function edit(AsignarTTaCuadrilla $asignarTTaCuadrilla)
	{
		if (!session()->get('usuarioReg_token_type')) {
			return redirect()->route('login.store');
		}

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector'); //Este dato viene a partir del logIn
		$rol = session()->get('usuarioReg_Rol'); //este dato viene a partir del logIn 2-supervisor 1-admin

		//si le mando sector en cero, es porqe es admin y trae 
		//solo los que pertenecen al servicio, sin importar el sector
		//Esto no se armo porque no hay nadie con sector cero es algo que quedo
		//sin armar funcionalidad por parte de la app

		if ($sec != 0) {
			//si sector es diff de cero, armo select solo con cuadrilla y traigo el nombre del sector
			$sector = DB::connection('GeaCorpico')->table('SECTOR')
				->where('SEC_ID', $sec)
				->get();
			$sectores = '';
			$cuadrillas = DB::connection('GeaCorpico')->table('TIPO_CUADRILLA')
				->where('TC_ID_SERVICIO', $serv)
				->where('TC_ID_SECTOR', $sec)
				->get();
		}

		//$list_tt_cuadrillas_asignadas = Http::get(config('constants.APP_API_HOST') . "/TIPO_TRABAJO_CUADRILLA/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		$list_tt_cuadrillas_asignadas = DB::connection('GeaCorpico')->table('TIPO_TRABAJO_CUADRILLA')
			->leftjoin('TIPO_CUADRILLA', 'TTC_ID_CUADRILLA', 'TC_ID')
			->leftjoin('TIPO_TRABAJO_OPERATIVO', 'TIT_ID', 'TTC_ID_TIPO_TRABAJO')
			->select('TIPO_TRABAJO_CUADRILLA.TTC_ID_CUADRILLA', 'TIPO_TRABAJO_OPERATIVO.TIT_DESCRIPCION', 'TIPO_TRABAJO_OPERATIVO.TIT_ID')
			->where('TC_ID', '2')
			->get()->toArray();
		$list_todos_tt = Http::get(config('constants.APP_API_HOST') . "/TIPO_TRABAJO_OPERATIVO/?servicio=$serv&sector=$sec&update=2018-01-01")->json();

		$cuadrillas = $cuadrillas->all();

		return view('asignar-tt-a-cuadrilla.edit', compact('cuadrillas'))
			->with('tts', $list_todos_tt)
			->with('cuadrillas', $cuadrillas)
			->with('sector', $sector)
			->with('sectores', $sectores)
			->with('tt_asignadas', $list_tt_cuadrillas_asignadas);
	}

	public function update(Request $request, $id)
	{
		$datos = $request->all();

		dd($datos);
		//ALMACERAR INFORMACION (ID CUADRILLA Y LOS IDS DE TIPO DE TRABAJO EN TABLA TIPO_TRABAJO_CUADRILLA)
		//  borrar asignacion previa y reinsertar

		$asignacionModificada = DB::connection('GeaCorpico')->table('TIPO_TRABAJO_CUADRILLA')
			->where('TTC_ID_CUADRILLA', '=', (int)$datos['id_cuadrilla'])
			->get();
		//dd($asignacionModificada);

		//			$asignacionModificada = DB::connection('GeaCorpico')->table('TIPO_TRABAJO_CUADRILLA')
		//			->where('TTC_ID_CUADRILLA','=', (int)$datos['id_cuadrilla'])
		//			->delete();

		return redirect()->route('AsignarTTaCuadrilla.index')
			->with('success', 'Usuario actualizado correctamente');
	}

	public function destroy(AsignarTTaCuadrilla $asignarTTaCuadrilla)
	{
		//
	}

	public function getCuadrillas($id_sector)
	{
		return DB::connection('GeaCorpico')->table('TIPO_CUADRILLA')
			->where('TC_ID_SECTOR', $id_sector)
			->get();
	}

	public function cuadrilla_ajax(Request $request)
	{
		$response = array();
		$response['tc_id'] = $request->get('TC_ID');

		$list_tt_cuadrillas_asignadas = DB::connection('GeaCorpico')->table('TIPO_TRABAJO_CUADRILLA')
			->leftjoin('TIPO_CUADRILLA', 'TTC_ID_CUADRILLA', 'TC_ID')
			->leftjoin('TIPO_TRABAJO_OPERATIVO', 'TIT_ID', 'TTC_ID_TIPO_TRABAJO')
			->select('TIPO_TRABAJO_CUADRILLA.TTC_ID_CUADRILLA', 'TIPO_TRABAJO_OPERATIVO.TIT_DESCRIPCION', 'TIPO_TRABAJO_OPERATIVO.TIT_ID', 'TIPO_TRABAJO_OPERATIVO.TIT_ABREVIATURA')
			->where('TC_ID', $response['tc_id'])
			->get()->toArray();

		$serv = session()->get('usuarioReg_Servicio'); //Si es supervisor, lo toma desde el login. Si es Admin, sector es = 0
		$sec = session()->get('usuarioReg_Sector');

		//$list_todos_tt = Http::get(config('constants.APP_API_HOST') . "/TIPO_TRABAJO_OPERATIVO/?servicio=$serv&sector=$sec&update=2018-01-01")->json();
		$list_todos_tt = DB::connection('GeaCorpico')->table('TIPO_TRABAJO_OPERATIVO')
			->leftjoin('TIPO_CUADRILLA', 'TTC_ID_CUADRILLA', 'TC_ID')
			->select('TIPO_TRABAJO_OPERATIVO.TIT_DESCRIPCION', 'TIPO_TRABAJO_OPERATIVO.TIT_ID', 'TIPO_TRABAJO_OPERATIVO.TIT_ABREVIATURA')
			->where('Servicio', $serv)
			->where('Sector', $sec)
			->get()->toArray();

		$response['ttasignados'] = $list_tt_cuadrillas_asignadas;
		$response['ttnoasignados'] = $list_todos_tt;

		return response()->json($response);
	}
}

resources/views/asignar-tt-a-cuadrilla/create.blade.php
<!DOCTYPE html>
@extends('adminlte::page')

@section('title', 'Asignacion TT a Cuadrilla')

@section('content_header')
    <h1>Asignacion TT a Cuadrilla</h1>
@stop


@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                  
                    <div class="card-body">
                        <form method="POST" action="{{ route('asignar-tt-a-cuadrilla.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('cuadrilla.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/asignar-tt-a-cuadrilla/edit.blade.php
@extends('adminlte::page')

@section('title', 'Asignar TT a Cuadrilla')
@section('plugins.Select2',true)

@section('content_header')
<h1>Asignar TT a Cuadrilla</h1>
@stop

@section('content')
<section class="content container-fluid">
	<div class="">
		<div class="col-md-12">

			@includeif('partials.errors')

			<div class="card card-body">
				<div class="card-header col-md-12">
					<span class="card-title col-md-12">Pasos a seguir: </span>
					<ol>
						<li> Seleccione una <strong>Cuadrilla</strong> </li>
						<li> Seleccione los <strong>Tipos de Trabajo</strong> asociados a la cuadrilla
							<ul>
								<li> Un clic en el tipo de trabajo de la ventana izquierda para asignar</li>
								<li> Un clic en el tipo de trabajo de la ventana derecha para borrar de la asignación</li>
							</ul>
						</li>
					</ol>

				</div>
				<div class="card-body">
					<form method="POST" action="{{ route('asignar-tt-a-cuadrilla.update', 1) }}" role="form" enctype="multipart/form-data">
						{{ method_field('PATCH') }}
						@csrf

						@include('asignar-tt-a-cuadrilla.form')

					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/asignar-tt-a-cuadrilla/form.blade.php
<!-- using https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox -->
<!-- common libraries -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<!-- plugin -->
<script src="https://www.virtuosoft.eu/code/bootstrap-duallistbox/bootstrap-duallistbox/v3.0.2/jquery.bootstrap-duallistbox.js"></script>

<link rel="stylesheet" type="text/css" href="https://www.virtuosoft.eu/code/bootstrap-duallistbox/bootstrap-duallistbox/v3.0.2/bootstrap-duallistbox.css">
<style>
	.moveall,
	.removeall {
		border: 1px solid #ccc !important;
	}

	.moveall::after {
		content: attr(title);
	}

	.removeall::after {
		content: attr(title);
	}

	/*  Custom styling form */
	.form-control option {
		padding: 10px;
		border-bottom: 1px solid #efefef;
	}
</style>

<div class="container">
	<div class="row col-md-12">
		<div class="box-body col-md-6">
			<div class="form-group col-md-12">
				{{ Form::label('Cuadrilla') }}
				<select name="cuadrilla" id="cuadrilla" class="form-control js-example-basic-single cuadrilla">
					<option value="#">Seleccione Cuadrilla</option>
					@foreach($cuadrillas as $cuadrilla)
					<option value="{{$cuadrilla->TC_ID}}">{{$cuadrilla->TC_DESCRIPCION}}</option>
					@endforeach
				</select>
			</div>
		</div>
	</div>
	<form id="asignacionTT">
		<input type="hidden" id="_token" name="_token" value="{{ csrf_token() }}">
		<select id="selectTT" multiple="multiple" size=10 name="selectTT[]" title="selectTT[]">
			@foreach($tts as $ttgeneral)
			<option value="{{$ttgeneral['TIT_ID']}}" @if (array_key_exists($ttgeneral['TIT_ID'], $tt_asignadas)!==false) selected="selected" @endif>
				{{$ttgeneral['TIT_DESCRIPCION']}} - {{$ttgeneral['TIT_ABREVIATURA']}}
			</option>
			@endforeach
		</select>
		<br>
	</form>
	<div class="row">
		<div class="col-md-6 offset-md-6">
			<!-- AsignarTTaCuadrilla.update-->
			<button type="submit" class="btn btn-primary w-100">Guardar</button>
		</div>
	</div>
</div>
</div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.js-example-basic-single').select2();

		$("#cuadrilla").change(function() {

			let tc_id = null;

			if ($("#cuadrilla option:selected").val())
				tc_id = $("#cuadrilla option:selected").val();

			if (tc_id) {
				$.ajax({
					data: {
						TC_ID: tc_id
					},
					dataType: 'json',
					type: 'POST',
					headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
					},
					url: '/asignar-tt-a-cuadrilla_ajax'
				}).done(function(data) { //metodo que se ejecuta cuando ajax ha completado su ejecucion             

					$('#selectTT').children().remove().end();
					$.each(data.ttasignados, function(i, item) {
						//console.log(item);
						console.log(item.TC_ID);
						console.log(item.TIT_DESCRIPCION + ' - ' + item.TIT_ABREVIATURA);
						$('#selectTT').append('<option selected value="' + item.TC_ID + '">' + item.TIT_DESCRIPCION + ' - ' + item.TIT_ABREVIATURA + '</option>');
					});

					$.each(data.ttnoasignados, function(i, item) {
						//console.log(item);
						console.log(item.TC_ID);
						console.log(item.TIT_DESCRIPCION + ' - ' + item.TIT_ABREVIATURA);
						$('#selectTT').append('<option value="' + item.TC_ID + '">' + item.TIT_DESCRIPCION + ' - ' + item.TIT_ABREVIATURA + '</option>');
					});

					cuadrillasSelect.bootstrapDualListbox('refresh');
				});
			} else {
				$('#selectTT').children().remove().end();
			}
		});

	});
</script>
<script>
	var cuadrillasSelect = $('select[name="selectTT[]"]').bootstrapDualListbox({
		nonSelectedListLabel: 'TT sin asignar',
		selectedListLabel: 'TT asignados a cuadrilla',
		preserveSelectionOnMove: 'moved',
		moveAllLabel: 'Mover todo',
		removeAllLabel: 'Borrar todo'
	});
</script>

resources/views/asignar-tt-a-cuadrilla/index.blade.php
@extends('adminlte::page')

@section('title', 'Asignar TT a Cuadrilla')

@section('content_header')
<h1>Asignar TT a Cuadrilla</h1>
@stop


@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: space-between; align-items: center;">

						<span id="card_title">
							{{ __('Lista') }}
						</span>

						<div class="float-right">
							<a href="{{ route('asignar-tt-a-cuadrilla.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
								{{ __('Nueva Cuadrilla') }}
							</a>
						</div>
					</div>
				</div>
				@if ($message = Session::get('success'))
				<div class="alert alert-success">
					<p>{{ $message }}</p>
				</div>
				@endif

				<div class="card-body">
					<div class="table-responsive">
						<table id="cuadrillas" class="table table-striped table-hover">
							<thead class="thead">
								<tr>
									<th></th>
									<th></th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach ($list_cuadrillas as $cuadrilla)
								<tr>
									<td>{{ $cuadrilla["TC_DESCRIPCION"] }} </td>
									<td>{{ $cuadrilla["TC_ID_SECTOR"] }} </td>
									<td>{{ $cuadrilla["TC_ID_SERVICIO"] }} </td>
									<td>
										<form action="{{ route('cuadrillas.destroy',$cuadrilla['TC_ID']) }}" method="POST">
											<a class="btn btn-sm btn-success" href="{{ route('cuadrillas.edit',$cuadrilla['TC_ID']) }}"><i class="fa fa-fw fa-edit"></i></a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
	$(document).ready(function() {
		$('#cuadrillas').DataTable({
			"language": {
				"search": "Buscar",
				"lengthMenu": "Mostrar _MENU_ registros por página",
				"info": "Mostrando página _PAGE_ de _PAGES_",
				"paginate": {
					"previous": "Anterior",
					"next": "Siguiente",
					"first": "Primero",
					"last": "Ultimo"
				}
			}
		});
	});
</script>
@endsection

resources/views/asignar-tt-a-cuadrilla/show.blade.php
@extends('adminlte::page')

@section('title', 'Cuadrilla')

@section('content_header')
    <h1>Ver Cuadrilla</h1>
@stop

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title"></span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('asignar-tt-a-cuadrilla.index') }}"> Volver</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Cuadrilla:</strong>
                            {{ $cuadrilla->descripcion }}
                        </div>
                        <div class="form-group">
                            <strong>Operario Id:</strong>
                            {{ $cuadrilla->operario_id }}
                        </div>
                        <div class="form-group">
                            <strong>Fecha:</strong>
                            {{ date('d-m-Y',strtotime($cuadrilla->fecha)) }}
                        </div>
                        <div class="form-group">
                            <strong>Servicio Id:</strong>
                            {{ $cuadrilla->servicio_id }}
                        </div>
                        <div class="form-group">
                            <strong>Sector Id:</strong>
                            {{ $cuadrilla->sector_id }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection