routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;
use App\Controllers;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SessionsController;

Route::get('/login', "App\Http\Controllers\SessionsController@create")->name('login.create');
Route::post('/login', "App\Http\Controllers\SessionsController@store")->name('login.store');
Route::post('/logout', [SessionsController::class,'logout']);
Route::get('/', "App\Http\Controllers\SessionsController@create")->name('login.create');

Route::get('home', "App\Http\Controllers\HomeController@index")->name('home');
Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);
Route::resource('cuadrillas', App\Http\Controllers\CuadrillaController::class);
Route::resource('sectores', App\Http\Controllers\SectorController::class);
// Route::resource('tipos-trabajo', App\Http\Controllers\TiposTrabajoController::class);
// Route::resource('motivos-trabajo', App\Http\Controllers\MotivosTrabajoController::class);
Route::resource('asignar-tt-a-cuadrilla', App\Http\Controllers\AsignarTTaCuadrillaController::class);
	//Route::resource('asignar-motivo-a-sector', App\Http\Controllers\AsignarMotivoASectorController::class);

Route::post('asignar-tt-a-cuadrilla_ajax', "App\Http\Controllers\AsignarTTaCuadrillaController@cuadrilla_ajax")->name('cuadrilla_ajax');

//});

resources/views/asignar-motivos-a-sectores/create.blade.php
<!DOCTYPE html>
@extends('adminlte::page')

@section('title', 'Asignacion Motivos a Sector')

@section('content_header')
<h1>Asignacion Motivos a Sectores</h1>
@stop


@section('content')
<section class="content container-fluid">
	<div class="row">
		<div class="col-md-12">

			@includeif('partials.errors')

			<div class="card card-default">

				<div class="card-body">
					<form method="POST" action="{{ route('asignar-motivos-a-sectores.store') }}" role="form" enctype="multipart/form-data">
						@csrf

						@include('sector.form')

					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/asignar-motivos-a-sectores/edit.blade.php
@extends('adminlte::page')

@section('title', 'Asignar Motivo a Sector')
@section('plugins.Select2',true)

@section('content_header')
<h1>Asignar Motivo a Sector</h1>
@stop

@section('content')
<section class="content container-fluid">
	<div class="">
		<div class="col-md-12">

			@includeif('partials.errors')

			<div class="card card-body">
				<div class="card-header col-md-12">
					<span class="card-title col-md-12">Pasos a seguir: </span>
					<ol>
						<li> Seleccione un <strong>Sector</strong> </li>
						<li> Seleccione los <strong>Motivos</strong> asociados al Sector
							<ul>
								<li> Un clic en el tipo de trabajo de la ventana izquierda para asignar</li>
								<li> Un clic en el tipo de trabajo de la ventana derecha para borrar de la asignación</li>
							</ul>
						</li>
					</ol>

				</div>
				<div class="card-body">
					<form method="POST" action="{{ route('asignar-motivo-a-sector.update', 1) }}" role="form" enctype="multipart/form-data">
						{{ method_field('PATCH') }}
						@csrf
						@include('asignar-motivo-a-sector.form')
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/asignar-motivos-a-sectores/form.blade.php
<!-- using https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox -->

<!-- common libraries -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<!-- plugin -->
<script src="https://www.virtuosoft.eu/code/bootstrap-duallistbox/bootstrap-duallistbox/v3.0.2/jquery.bootstrap-duallistbox.js"></script>

<link rel="stylesheet" type="text/css" href="https://www.virtuosoft.eu/code/bootstrap-duallistbox/bootstrap-duallistbox/v3.0.2/bootstrap-duallistbox.css">
<style>
	/* .moveall,
	.removeall {
		border: 1px solid #ccc !important;

		&:hover {
			background: #efefef;
		}
	} */

	.moveall::after {
		content: attr(title);

	}

	.removeall::after {
		content: attr(title);
	}

	/* // Custom styling form */
	.form-control option {
		padding: 10px;
		border-bottom: 1px solid #efefef;
	}
</style>

<div class="container">
	<div class="row col-md-12">
		<div class="box-body col-md-3"></div>
		<div class="box-body col-md-6">
			<div class="form-group col-md-12">
				{{ Form::label('Cuadrilla') }}
				<select name="id_cuadrilla" id="id_cuadrilla" class="form-control js-example-basic-single">
					<option value="#">Seleccione Cuadrilla</option>
					@foreach($list_cuadrillas as $cuadrilla)
					<option value="{{$cuadrilla['TC_ID']}}">{{$cuadrilla['TC_DESCRIPCION']}}</option>
					@endforeach
				</select>
			</div>
		</div>
		<div class="box-body col-md-3"></div>
	</div>
	<form id="asignacionTT">
		<select multiple="multiple" size=10 name="selectTT[]" title="selectTT[]">
			@foreach($tts as $ttgeneral)
			<option value="{{$ttgeneral['TIT_ID']}}">{{$ttgeneral['TIT_DESCRIPCION']}} - {{$ttgeneral['TIT_ABREVIATURA']}}</option>
			@endforeach
		</select>
		<br>
	</form>
	<div class="row">
		<div class="col-md-6 offset-md-6">
			<!-- AsignarTTaCuadrilla.update-->
			<button type="submit" class="btn btn-primary w-100">Guardar</button>
		</div>
	</div>
</div>
</div>
</div>

<script>
	var demo1 = $('select[name="selectTT[]"]').bootstrapDualListbox({
		nonSelectedListLabel: 'TT sin asignar',
		selectedListLabel: 'TT asignados a cuadrilla',
		preserveSelectionOnMove: 'moved',
		moveAllLabel: 'Mover todo',
		removeAllLabel: 'Borrar todo'
	});

	$("#asignacionTT").submit(function() {
		alert($('[name="selectTT[]"]').val());
		return false;
	});
</script>
<!-- Agregamos la libreria Jquery -->
<!--<script type="text/javascript" src="jquery-3.2.0.min.js"></script>-->
<script type="text/javascript">
	$(document).ready(function() {


		// var asignados = $('#selectTT[]');
		// var asignados_sel = $('#selectTT[]_sel');

		//Ejecutar accion al cambiar de opcion en el select de las bandas
		$('#id_cuadrilla').change(function() {
			var id_cuadrilla = $(this).val(); //obtener el id seleccionado
			var url = "/asignar-tt-a-cuadrilla/obtenerCuadrillas/" + id_cuadrilla;
			console.log(url);
			if (id_cuadrilla !== '') { //verificar haber seleccionado una opcion valida

				$.ajax({
					data: {
						id_cuadrilla: id_cuadrilla
					}, //variables o parametros a enviar, formato => nombre_de_variable:contenido
					dataType: 'html', //tipo de datos que esperamos de regreso
					type: 'POST', //mandar variables como post o get
					url: url //url que recibe las variables
				}).done(function(data) { //metodo que se ejecuta cuando ajax ha completado su ejecucion             

					asignados.html(data); //establecemos el contenido html de asignados con la informacion que regresa ajax             
					asignados.prop('disabled', false); //habilitar el select
				});


			} else { //en caso de seleccionar una opcion no valida
				asignados.val(''); //seleccionar la opcion "- Seleccione -", osea como reiniciar la opcion del select
				asignados.prop('disabled', true); //deshabilitar el select
			}
		});

		//mostrar una leyenda 
		$('#asignados').change(function() {
			$('#selectTT[]_sel').html($(this).val() + ' - ' + $('#asignados option:selected').text());
		});

	});
</script>

resources/views/asignar-motivos-a-sectores/index.blade.php
@extends('adminlte::page')

@section('title', 'Asignar TT a Cuadrilla')

@section('content_header')
<h1>Asignar TT a Cuadrilla</h1>
@stop


@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: space-between; align-items: center;">

						<span id="card_title">
							{{ __('Lista') }}
						</span>

						<div class="float-right">
							<a href="{{ route('asignar-tt-a-cuadrilla.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
								{{ __('Nueva Cuadrilla') }}
							</a>
						</div>
					</div>
				</div>
				@if ($message = Session::get('success'))
				<div class="alert alert-success">
					<p>{{ $message }}</p>
				</div>
				@endif

				<div class="card-body">
					<div class="table-responsive">
						<table id="cuadrillas" class="table table-striped table-hover">
							<thead class="thead">
								<tr>

									<th></th>
									<th></th>
									<th></th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach ($list_cuadrillas as $cuadrilla)

								<tr>
									<td>{{ $cuadrilla["TC_DESCRIPCION"] }} </td>
									<td>{{ $cuadrilla["TC_ID_SECTOR"] }} </td>
									<td>{{ $cuadrilla["TC_ID_SERVICIO"] }} </td>
									<td>
										<form action="{{ route('cuadrillas.destroy',$cuadrilla['TC_ID']) }}" method="POST">
											<a class="btn btn-sm btn-primary " href="{{ route('cuadrillas.show',$cuadrilla['TC_ID']) }}"><i class="fa fa-fw fa-eye"></i></a>
											<a class="btn btn-sm btn-success" href="{{ route('cuadrillas.edit',$cuadrilla['TC_ID']) }}"><i class="fa fa-fw fa-edit"></i></a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
	$(document).ready(function() {
		$('#cuadrillas').DataTable({
			"language": {
				"search": "Buscar",
				"lengthMenu": "Mostrar _MENU_ registros por página",
				"info": "Mostrando página _PAGE_ de _PAGES_",
				"paginate": {
					"previous": "Anterior",
					"next": "Siguiente",
					"first": "Primero",
					"last": "Ultimo"

				}
			}
		});
	});
</script>
@endsection

resources/views/asignar-motivos-a-sectores/show.blade.php
@extends('adminlte::page')

@section('title', 'Cuadrilla')

@section('content_header')
<h1>Ver Cuadrilla</h1>
@stop

@section('content')
<section class="content container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="float-left">
						<span class="card-title"></span>
					</div>
					<div class="float-right">
						<a class="btn btn-primary" href="{{ route('asignar-tt-a-cuadrilla.index') }}"> Volver</a>
					</div>
				</div>

				<div class="card-body">

					<div class="form-group">
						<strong>Cuadrilla:</strong>
						{{ $cuadrilla->descripcion }}
					</div>
					<div class="form-group">
						<strong>Operario Id:</strong>
						{{ $cuadrilla->operario_id }}
					</div>
					<div class="form-group">
						<strong>Fecha:</strong>
						{{ date('d-m-Y',strtotime($cuadrilla->fecha)) }}
					</div>
					<div class="form-group">
						<strong>Servicio Id:</strong>
						{{ $cuadrilla->servicio_id }}
					</div>
					<div class="form-group">
						<strong>Sector Id:</strong>
						{{ $cuadrilla->sector_id }}
					</div>

				</div>
			</div>
		</div>
	</div>
</section>
@endsection