routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Http;
use App\Controllers;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\SessionsController;

Route::get('/login', "App\Http\Controllers\SessionsController@create")->name('login.create');
Route::post('/login', "App\Http\Controllers\SessionsController@store")->name('login.store');
Route::post('/logout', [SessionsController::class,'logout']);
Route::get('/', "App\Http\Controllers\SessionsController@create")->name('login.create');

Route::get('home', "App\Http\Controllers\HomeController@index")->name('home');
Route::resource('usuarios', App\Http\Controllers\UsuarioController::class);
Route::resource('cuadrillas', App\Http\Controllers\CuadrillaController::class);
Route::resource('sectores', App\Http\Controllers\SectorController::class);
// Route::resource('tipos-trabajo', App\Http\Controllers\TiposTrabajoController::class);
// Route::resource('motivos-trabajo', App\Http\Controllers\MotivosTrabajoController::class);
Route::resource('asignar-tt-a-cuadrilla', App\Http\Controllers\AsignarTTaCuadrillaController::class);
	//Route::resource('asignar-motivo-a-sector', App\Http\Controllers\AsignarMotivoASectorController::class);

Route::post('asignar-tt-a-cuadrilla_ajax', "App\Http\Controllers\AsignarTTaCuadrillaController@cuadrilla_ajax")->name('cuadrilla_ajax');

//});

resources/views/sectores/create.blade.php
@extends('adminlte::page')

@section('title', 'Sector')

@section('content_header')
<h1>Sector</h1>
@stop


@section('content')
<section class="content container-fluid">
	<div class="row">
		<div class="col-md-12">

			@includeif('partials.errors')

			<div class="card card-default">
				<div class="card-header">
					<span class="card-title">Nuevo Sector</span>
				</div>
				<div class="card-body">
					<form method="POST" action="{{ route('sectores.store') }}" role="form" enctype="multipart/form-data">
						@csrf

						@include('sectores.form')

					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/sectores/edit.blade.php
@extends('adminlte::page')

@section('title', 'Sector')

@section('content_header')
<h1>Modificar Sector</h1>
@stop

@section('content')
<section class="content container-fluid">
	<div class="">
		<div class="col-md-12">

			@includeif('partials.errors')

			<div class="card card-default">
				<div class="card-header">
					<span class="card-title">Modificar Sector</span>
				</div>
				<div class="card-body">
					<form method="POST" action="{{ route('sectores.update', $id) }}" role="form" enctype="multipart/form-data">
						{{ method_field('PATCH') }}
						@csrf

						@include('sectores.form')

					</form>
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

resources/views/sectores/form.blade.php
<div class="box box-info padding-1">
	<div class="box-body row">

		<div class="form-group col-md-4">
			{{ Form::label('Servicio:') }}<br>
			{{$nombreServicio}}
		</div>

		<div class="form-group col-md-4">
			{{ Form::label('nombre del sector') }}
			{{ Form::text('descripcion', $nombreSector == '' ? null : $nombreSector, ['class' => 'form-control' . ($errors->has('descripcion') ? ' is-invalid' : ''), 'placeholder' => 'Descripcion']) }}
		</div>

	</div>
	<div class="box-footer mt20">
		<button type="submit" class="btn btn-primary">Guardar</button>
	</div>
</div>

resources/views/sectores/index.blade.php
@extends('adminlte::page')

@section('title', 'Sectores')

@section('content_header')
<h1>Sectores</h1>
@stop

@section('content')
<div class="container-fluid">
	@if (session('success'))
	<div class="alert alert-success" role="success">
		{{ session('success') }}
	</div>
	@endif
	@if (session('error'))
	<div class="alert alert-error" role="error">
		{{ session('error') }}
	</div>
	@endif

	<div class="row">
		<div class="col-sm-12">
			<div class="card">
				<div class="card-header">
					<div style="display: flex; justify-content: space-between; align-items: center;">

						<span id="card_title">
							{{ __('Lista de Sectores') }}s
						</span>

						<div class="float-right">
							<a href="{{ route('sectores.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
								{{ __('Nuevo Sector') }}
							</a>
						</div>
					</div>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table id="sectores" class="table table-striped table-hover">
							<thead class="thead">
								<tr>
									<th>Descripcion</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach ($arraySectores as $sector)
								<tr>
									<td>{{ $sector['SEC_DESCRIPCION'] }}</td>
									<td>
										<form action="{{ route('sectores.destroy',$sector['SEC_ID']) }}" method="POST">
											<a class="btn btn-sm btn-success" href="{{ route('sectores.edit',$sector['SEC_ID']) }}"><i class="fa fa-fw fa-edit"></i> </a>
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-danger btn-sm borrar"><i class="fa fa-fw fa-trash"></i> </button>
										</form>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
@endsection
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css">
@endsection
@section('js')
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>

<script>
	$(document).ready(function() {
		$('#sectores').DataTable({
			"language": {
				"search": "Buscar",
				"lengthMenu": "Mostrar _MENU_ registros por página",
				"info": "Mostrando página _PAGE_ de _PAGES_",
				"paginate": {
					"previous": "Anterior",
					"next": "Siguiente",
					"first": "Primero",
					"last": "Ultimo"

				}
			}
		});
	});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>

<script type="text/javascript">
		$('.borrar').click(function(event) {
			var form = $(this).closest("form");
			var name = $(this).data("name");
			event.preventDefault();
			swal({
					title: `Eliminar Sector`,
					text: "Este sector puede tener motivos asignados. DESEA CONTINUAR?",
					icon: "warning",
					buttons: true,
					dangerMode: true,
				})

				.then((willDelete) => {
					if (willDelete) {
						form.submit();
					}
				});
		});
	</script>
@endsection

resources/views/sectores/show.blade.php
@extends('adminlte::page')

@section('title', 'Sector')

@section('content_header')
<h1>Ver Sector</h1>
@stop

@section('content')
<section class="content container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="float-left">
						<span class="card-title">Mostrar Sector</span>
					</div>
					<div class="float-right">
						<a class="btn btn-primary" href="{{ route('sectores.index') }}"> Volver</a>
					</div>
				</div>

				<div class="card-body">

					<div class="form-group">
						<strong>Servicio Id:</strong>
						{{ $sector->servicio_id }}
					</div>
					<div class="form-group">
						<strong>Descripcion:</strong>
						{{ $sector->descripcion }}
					</div>

				</div>
			</div>
		</div>
	</div>
</section>
@endsection